In [2]:
import numpy as np

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### linspace verilen aralıkta verilen sayı kadar eşit aralıklı değer oluşturur

In [8]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.random.randn(8)

array([-1.53782653, -0.57566056, -0.10284573, -0.49388901, -0.71704902,
       -0.96253774,  0.02726157,  0.37110009])

In [11]:
np.random.randn(2,2)

array([[ 0.53755667, -0.09343775],
       [-0.0894871 ,  0.10621117]])

In [12]:
np.random.choice(np.arange(0,20),(4,4)) #0-20 arasında sayılarla oluşturulmuş TEK BOYUTLU diziden rastgele elemanlar alarak 4x4lük matrix oluşturur.

array([[10, 16, 11, 13],
       [10,  3,  4, 12],
       [17, 17,  7, 19],
       [ 3,  2, 14, 19]])

### np.random.randn() rastgle float değerler döndürürken np.random.randint() ile rastgele integer değerler döndürülebilir.

In [13]:
np.random.randint(0,10)

3

In [14]:
np.random.randint(0,20,4)

array([18, 10,  2, 14])

In [15]:
np.random.randint(20,100,(3,5))

array([[79, 52, 48, 73, 99],
       [28, 57, 20, 59, 42],
       [57, 23, 38, 68, 69]])

In [16]:
numDizi=np.arange(30)

In [17]:
numDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [18]:
randomDizi=np.random.randint(0,100,20)

In [19]:
randomDizi

array([21, 90, 17, 61, 51, 92, 70, 97, 37, 14,  1, 62, 57, 51, 47, 84, 30,
       83, 15, 55])

## Numpy Dizi Metodları

In [20]:
reshapeDizi=numDizi.reshape(5,6)

In [21]:
reshapeDizi.shape

(5, 6)

In [22]:
randomDizi.max()

97

In [23]:
randomDizi.min()

1

In [24]:
randomDizi.argmax() #max elemanın indexini verir

7

In [25]:
randomDizi.argmin() #min elemanın indexini verir

10

## Numpy İndexing

#### numpy dizilerinde slicing(diziniz bir parçasını başka değişkene eşitleme) yapılırken oluşturulan yeni dizinin adresi eski diziden aldığı değerlerin adresine eşitlenir bu yüzden yeni dizide yapılacak değişiklikler aynı şekilde eski diziye yansır. Eğer yeni dizideki değişimlerin eski diziyi etkilemesini istemiyorsak .copy() fonksiyonunu kullanabiliriz.

In [26]:
dizi=np.arange(0,25)

In [27]:
dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
diziparcasi=dizi[3:6]

In [29]:
diziparcasi[:]

array([3, 4, 5])

In [30]:
diziparcasi[:] = 500

In [31]:
diziparcasi

array([500, 500, 500])

In [32]:
dizi

array([  0,   1,   2, 500, 500, 500,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [33]:
ornek=np.arange(25)

In [34]:
ornekCopy=ornek.copy()

In [35]:
ornekCopySlicing=ornekCopy[12:16]

In [36]:
ornekCopySlicing[:]=500

In [37]:
ornekCopySlicing

array([500, 500, 500, 500])

In [38]:
ornekCopy

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11, 500,
       500, 500, 500,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [39]:
ornek

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Matrix İndexing

In [40]:
matrix=np.arange(25).reshape(5,5)

In [41]:
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
matrix[[2,4,0]] #2, 4, ve 0. indexleri tek tek verir (fancy indexing)

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [ 0,  1,  2,  3,  4]])

In [43]:
matrix[[2,4,0]][0] #fancy indexing ten sonra verilen index isteği fancy index elemanlarını bir liste gibi tanır ve indexlemeyi 
#oluşan bu yeni elemanlar arasında yapar.

array([10, 11, 12, 13, 14])

In [44]:
matrix[[2,4,0],[0]] #fancy indexing elemanlarını elaman gibi tanımak yerine eski arrayın belli bir sütununu almak için

array([10, 20,  0])

## Dizi Operasyonları

In [45]:
yeniDizi=np.random.randint(0,30,10)

In [46]:
yeniDizi

array([17, 21, 11, 18, 12, 26, 10, 14,  2, 10])

In [47]:
x=yeniDizi<10

In [48]:
yeniDizi[x]

array([2])

In [49]:
dizi=np.arange(1,25)

In [50]:
dizi+dizi

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [51]:
dizi*dizi

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

In [52]:
dizi-dizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [53]:
dizi/dizi

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [54]:
dizi + 4

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28])

In [55]:
np.arange(10)/np.arange(10) # işlem sırasında 0/0 a rastlayacak ve bu durumda hata vermek yerine yeni diziye nan girdisi yapacak

<ipython-input-55-59fd4ba59709>:1: RuntimeWarning: invalid value encountered in true_divide
  np.arange(10)/np.arange(10) # işlem sırasında 0/0 a rastlayacak ve bu durumda hata vermek yerine yeni diziye nan girdisi yapacak


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [56]:
np.sqrt(dizi) #karekök alma

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949])

## Numpy İterating (sample :3d to 1d)

In [57]:
tdArray=np.arange(0,8).reshape(2,2,2)

In [58]:
tdArray

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

#### 3d tdArray dizisini 1d gibi içinde gezip tek tek yazdır :

In [59]:
for i in (np.nditer(tdArray)):
    print(i,end="-")

0-1-2-3-4-5-6-7-

#### 3d arraydaki elemanları index bilgisi ile alma numalandırarak yazdırma :

In [60]:
for idx,i in (np.ndenumerate(tdArray)):
    print(idx,i)

(0, 0, 0) 0
(0, 0, 1) 1
(0, 1, 0) 2
(0, 1, 1) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 1, 0) 6
(1, 1, 1) 7


In [61]:
conc1=np.arange(6).reshape(2,3)

In [62]:
conc2=np.arange(6,12).reshape(2,3)

In [63]:
np.concatenate((conc1,conc2),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [64]:
np.stack((conc1,conc2),axis=1)

array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])

In [65]:
np.stack((conc1.reshape(6),conc2.reshape(6)),axis=1) #her indexte iki array içinde elemanları alıp yan yana yazarak birleştirir.

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [66]:
np.vstack((conc1,conc2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [67]:
np.hstack((conc1,conc2))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [68]:
np.dstack((conc1.reshape(6),conc2.reshape(6)))#In[65] da yazılan kodla tek farkı orada 2d çıktı alırken burada 3d çıktı alıyoruz

array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8],
        [ 3,  9],
        [ 4, 10],
        [ 5, 11]]])

## Array Split

In [69]:
splArray=np.arange(27)

In [70]:
np.array_split(splArray,3)

[array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14, 15, 16, 17]),
 array([18, 19, 20, 21, 22, 23, 24, 25, 26])]

In [71]:
np.array_split(splArray.reshape(3,9),3)

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [72]:
np.array_split(splArray.reshape(3,3,3),3)

[array([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]]),
 array([[[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]]),
 array([[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])]

In [73]:
print(splArray.reshape(3,9))
np.array_split(splArray.reshape(3,9),3,axis=1)
#3x9 matrixten eksen=1 den split işlemi yaparsak ilk satırda ilgili split işlemini yapıp aynı işlemi alt satırlara uygular ve
#iç kümede aynı indexe denk gelen elemanlar ile yeni bir matrix çıktısı alınır
#axis=1 yerine np.hsplit axis=0 yerinede np.vsplit kullanılabilir.

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]


[array([[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]]),
 array([[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23]]),
 array([[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26]])]

In [74]:
t=np.random.randint(1,15,10)

In [75]:
t

array([ 9, 14,  1,  1,  1,  1,  8, 13, 10, 13])

In [80]:
np.where(t==13) #t nin 13olan elemanlarının indexini verir

(array([7, 9], dtype=int64),)

In [77]:
np.where(t%2==1)

(array([0, 2, 3, 4, 5, 7, 9], dtype=int64),)

## SORT

In [78]:
np.sort(t)

array([ 1,  1,  1,  1,  8,  9, 10, 13, 13, 14])

In [79]:
np.sort(t.reshape(5,2)) #birden fazla boyutlu dizilerde sadece dizinin içinde sıralama yapar üst kümelere karışmaz

array([[ 9, 14],
       [ 1,  1],
       [ 1,  1],
       [ 8, 13],
       [10, 13]])